[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
nftCollection_addr = "0xbc81658ba0d9ffdd0663433259ce06e5c3af6ccae6fb982cc301adf3cdda3687"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
